<?php 

//use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
Use App\Models\Exercise;

	class exerciseSeeder extends Seeder {

		public function run()
		{
			$exercises = array(
				['body' => 'Chest', 'exercise' => 'Flat Bench Press Barbell'],
				['body' => 'Chest', 'exercise' => 'Incline Barbell Bench Press'],
				['body' => 'Chest', 'exercise' => 'Flat Dumbbell Bench Press'],
				['body' => 'Chest', 'exercise' => 'Incline Dumbbell Bench Press'],
				['body' => 'Chest', 'exercise' => 'Dumbbell Flat Bench Flys'],
				['body' => 'Chest', 'exercise' => 'Incline Bench Dumbbell Flys'],
				['body' => 'Chest', 'exercise' => 'Dips'],
				['body' => 'Chest', 'exercise' => 'Weighted Dips'],
				['body' => 'Chest', 'exercise' => 'Cable Flys'],
				['body' => 'Chest', 'exercise' => 'Incline Cable Flys'],
				['body' => 'Chest', 'exercise' => 'Decline Cable Flys'],
				['body' => 'Back', 'exercise' => 'Deadlifts'],
				['body' => 'Back', 'exercise' => 'Sumo Deadlifts'],
				['body' => 'Back', 'exercise' => 'Single Leg Dumbbell Deadlift'],
				['body' => 'Back', 'exercise' => 'Dumbbell Deadlift'],
				['body' => 'Back', 'exercise' => 'Barbell Rows'],
				['body' => 'Back', 'exercise' => 'Close Grip Barbell Rows'],
				['body' => 'Back', 'exercise' => 'T-Bar Rows'],
				['body' => 'Back', 'exercise' => 'Hammer Strength Lateral Rows'],
				['body' => 'Back', 'exercise' => 'Seated Rows'],
				['body' => 'Back', 'exercise' => 'Lateral Pull Downs'],
				['body' => 'Back', 'exercise' => 'Close Grip Lateral Pull Downs'],
				['body' => 'Back', 'exercise' => 'Pull Ups'],
				['body' => 'Back', 'exercise' => 'Weighted Pull Ups'],
				['body' => 'Back', 'exercise' => 'Close Grip Pull Ups'],
				['body' => 'Back', 'exercise' => 'Dumbbell Rows'],
				['body' => 'Back', 'exercise' => 'Single Arm Dumbbell Rows'],
				['body' => 'Back', 'exercise' => 'Dumbbell Pullovers'],
				['body' => 'Shoulders', 'exercise' => 'Barbell Military Press'],
				['body' => 'Shoulders', 'exercise' => 'Seated Barbell Military Press'],
				['body' => 'Shoulders', 'exercise' => 'Dumbbell Military Press'],
				['body' => 'Shoulders', 'exercise' => 'Seated Dumbbell Military Press'],
				['body' => 'Shoulders', 'exercise' => 'Arnold Presses'],
				['body' => 'Shoulders', 'exercise' => 'Seated Arnold Presses'],
				['body' => 'Shoulders', 'exercise' => 'Side Lateral Raises'],
				['body' => 'Shoulders', 'exercise' => 'Front Dealt Raises'],
				['body' => 'Shoulders', 'exercise' => 'Rear Dealt Raises'],
				['body' => 'Shoulders', 'exercise' => 'Cable Read Dealt Flys'],
				['body' => 'Shoulders', 'exercise' => 'Iron Crosses'],
				['body' => 'Shoulders', 'exercise' => 'Dumbbell Shrugs'],
				['body' => 'Shoulders', 'exercise' => 'Barbell Shrugs'],
				['body' => 'Shoulders', 'exercise' => 'Rear Barbell Shrugs'],
				['body' => 'Legs', 'exercise' => 'Barbell Squats'],
				['body' => 'Legs', 'exercise' => 'Dumbbell Squats'],
				['body' => 'Legs', 'exercise' => 'Hack Squats'],
				['body' => 'Legs', 'exercise' => 'Barbell Lunges'],
				['body' => 'Legs', 'exercise' => 'Dumbbell Lunges'],
				['body' => 'Legs', 'exercise' => 'Walking Lunges'],
				['body' => 'Legs', 'exercise' => 'Lunge Squats'],
				['body' => 'Legs', 'exercise' => 'Leg Extensions'],
				['body' => 'Legs', 'exercise' => 'Seated Leg Curls'],
				['body' => 'Legs', 'exercise' => 'Leg Press'],
				['body' => 'Legs', 'exercise' => 'Single Leg Squat'],
				['body' => 'Legs', 'exercise' => 'Single Leg Press'],
				['body' => 'Legs', 'exercise' => 'Standing Calf Raises'],
				['body' => 'Legs', 'exercise' => 'Seated Calf Raises'],
				['body' => 'Legs', 'exercise' => 'Leg Press Machine Calf Raises'],
				['body' => 'Arms', 'exercise' => 'Straight Bar Curls'],
				['body' => 'Arms', 'exercise' => 'EZ Bar Curls'],
				['body' => 'Arms', 'exercise' => 'Dumbbell Curls'],
				['body' => 'Arms', 'exercise' => 'Hammer Curls'],
				['body' => 'Arms', 'exercise' => 'Cable Rope Curls'],
				['body' => 'Arms', 'exercise' => 'Preacher Curls'],
				['body' => 'Arms', 'exercise' => 'Single Arm Preacher Curls'],
				['body' => 'Arms', 'exercise' => 'Seated Incline Bench Curls'],
				['body' => 'Arms', 'exercise' => 'Reverse Grip Curls'],
				['body' => 'Arms', 'exercise' => 'Skull Crushers'],
				['body' => 'Arms', 'exercise' => 'Incline Bench Skull Crushers'],
				['body' => 'Arms', 'exercise' => 'Close Grip Bench Press'],
				['body' => 'Arms', 'exercise' => 'Incline Close Grip Bench Press'],
				['body' => 'Arms', 'exercise' => 'Single Arm Dumbbell Kickback'],
				['body' => 'Arms', 'exercise' => 'Dumbbell Kickbacks'],
				['body' => 'Arms', 'exercise' => 'Cable Triceps extensions'],
				['body' => 'Arms', 'exercise' => 'Reverse Grip Tricep Exensions'],
				['body' => 'Arms', 'exercise' => 'Close Grip Tricep Extensions'],
				['body' => 'Arms', 'exercise' => 'Cable Rope Extensions'],
				['body' => 'Core', 'exercise' => 'Cable Wood Chop High to Low'],
				['body' => 'Core', 'exercise' => 'Cable Wood Chop Low to High'],
				['body' => 'Core', 'exercise' => 'Cable Wood Chop'],
				['body' => 'Core', 'exercise' => 'Dumbbell Wood Chop Low to High'],
				['body' => 'Core', 'exercise' => 'Dumbbell Rotation'],
				['body' => 'Core', 'exercise' => 'Lunge Position Dumbbell Rotations'],
				['body' => 'Core', 'exercise' => 'Cable Crunches'],
				['body' => 'Core', 'exercise' => 'Weighted Crunches'],
				['body' => 'Core', 'exercise' => 'Weighted Crunches Decline Bench'],
				['body' => 'Core', 'exercise' => 'Hanging Knee Raises'],
				['body' => 'Core', 'exercise' => 'Hanging Knee Raises with weight'],
				['body' => 'Core', 'exercise' => 'Hanging Leg Raises'],
				['body' => 'Core', 'exercise' => 'Hanging Leg Raises with weight']
			);

			foreach($exercises as $exercise)
			{
				Exercise::create($exercise);
			}
		}
	}